server:
  port: 8080
spring:
  datasource:
    initialization-mode: always
    # 可以指定初始化脚本路径，默认schema.sql
    schema: classpath:schema-mysql.sql
    type: com.alibaba.druid.pool.DruidDataSource

    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat,wall,slf4j
      driver-class-name: com.mysql.cj.jdbc.Driver
      #基本属性
      url: jdbc:mysql://localhost:3306/exampledb12
      username: root
      password: exampledb20
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20


#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  #  config-location: classpath:mybatis/mybatis-config.xml

  type-aliases-package: com.example.demo.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 二级缓存的总开关
    cache-enabled: true
    #    SESSION/STATEMENT"
    localCacheScope: STATEMENT

logging:
  config: classpath:logback-spring.xml
  level:
    root: debug